version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: xclone
      POSTGRES_PASSWORD: "-3kxxoWd6L2dOXW-02_pGZSCMQnVCOUI"
    volumes:
      - xclone_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "G5NfsYq4d4rTPXXnDE3U7uTrzROdnIjA"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  xclone_data:
